# permissions for end users to view promotionstrategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: promotionstrategy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: promoter
    app.kubernetes.io/part-of: promoter
    app.kubernetes.io/managed-by: kustomize
  name: promotionstrategy-viewer-role
rules:
- apiGroups:
  - promoter.argoproj.io
  resources:
  - promotionstrategies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - promotionstrategies/status
  verbs:
  - get
