apiVersion: promoter.argoproj.io/v1alpha1
kind: ProposedCommit
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: proposedcommit-sample
spec:
  repositoryRef:
    owner: zachaller
    name: promoter-testing
    scmProviderRef:
      name: scmprovider-sample
  proposedBranch: environment/development-next
  activeBranch: environment/development
  commitStatuses:
    - key: healthy
