name: test-e2e
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        kubernetes-minor-version:
          - 1.28
          - 1.29
          - 1.30.0
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # pin@v5
        with:
          go-version: "1.22"
          # see https://github.com/actions/setup-go?tab=readme-ov-file#caching-dependency-files-and-build-outputs
          cache-dependency-path: |
            go.sum
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          k8s-version: v${{ matrix.kubernetes-minor-version }}
          name: kind-${{ matrix.kubernetes-minor-version }}
          version: v0.23.0
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: make
      - name: Run E2E-Tests
        run: make test-e2e